services:
  - type: web
    name: blanc-manger-coco
    runtime: node

    buildCommand: corepack enable && pnpm install --frozen-lockfile && pnpm --filter @workspace/blanc-manger-coco run build && pnpm --filter @workspace/api-server run build

    startCommand: node --enable-source-maps ./artifacts/api-server/dist/index.mjs

    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
